### ISSUE TITLE
How to load libexample.so at other application?

### ISSUE THREAD

**Issue by erwangccc** [asprecic/mediapipe-qt-integration-example#1]
Hi, @asprecic 

I want to compile libexample.so and use hand_pose at my own application not at QT. And how to call the API to do hand pose, do you have a demo code to share?

Thanks in advance.

**Comment by asprecic** [comment]
Compiling libexample.so is the same for any C++ application that you want to use, I just used Qt as it's easiest to demonstrate.
So, just use the header file, and libexample.so, link it, add it to include in whatever you're using, make, cmake or g++/clang CLI itself.
As for a demo, I don't have one, but you can use the mpintegrationexample.cpp as a starting point to see how to use the API, call which functions etc.
The basic jist of it is this:
// Create object
MPIntegrationExample example;
// use setGraph to select which example you want to use (in your case hand pose)
example.setGraph(StyleClass::Graphs::SelfieSegmentation);
// call process to process images one by one
uint8_t* data = m_mp->Process(input_img.data(), input_img.width(), input_img.height());
// pointer data now points to image data of processed returned image, whose width and height is the same as input image

**Comment by akashnambiar** [comment]
So I'm trying to do something similar in running the example implementation. I'm running this command: "g++ example_impl.cpp -l libexample.so". However I get errors saying that certain mediapipe files don't exist. Is it possible to compile like this, or are there more steps I should be doing?

Any help would be much appreciated, thanks!

**Comment by asprecic** [comment]
You have to use bazel to compile mediapipe, as is written in the step by step guide in both this repo and my forked mediapipe repo.

**Comment by akashnambiar** [comment]
Sorry for the misunderstanding, but just to clarify, you can't use clang/make/etc by itself with libexample.so(generated with bazel). You need to generate libexample.so and then use bazel to run mediapipe?

**Comment by asprecic** [comment]
Libexample.so should be compiled statically and everything should be self contained in there. You can run ldd libexample.so to confirm.
If you check the qmake (.pro file) in this repo, you can see that I am simply linking against libexample.so and nothing else.
Also, in your previous command, did you include the corresponding header files for libexample?
Can you post exactly what mediapipe files are missing?

**Comment by asprecic** [comment]
The header file is in mediapipe/examples/desktop/libexample/example.h
Libexample.so and example.h should be the only thing you need

**Comment by akashnambiar** [comment]
Yah I included the corresponding file header, these are the files missing (in example_impl.h):

#include "absl/status/status.h"
#include "mediapipe/framework/calculator_framework.h"
